"""Synchronous by design: env.py calls asyncio.run, which raises inside a running loop."""

import asyncio

import pytest
from alembic import command
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import text
from sqlalchemy.engine import make_url
from sqlalchemy.ext.asyncio import create_async_engine
from sqlalchemy.pool import NullPool

from tests.conftest import alembic_config, derive_test_database_url

DATABASE = "underwrite_migrations_test"

TABLES = "select table_name from information_schema.tables where table_schema = 'public'"
ENUM_TYPES = """
select t.typname from pg_type t
join pg_namespace n on n.oid = t.typnamespace
where n.nspname = 'public' and t.typtype = 'e'
"""


def url_for(database: str) -> str:
    return (
        make_url(derive_test_database_url())
        .set(database=database)
        .render_as_string(hide_password=False)
    )


def names(url: str, query: str) -> set[str]:
    async def run() -> set[str]:
        engine = create_async_engine(url, poolclass=NullPool)
        try:
            async with engine.connect() as connection:
                return {row[0] for row in await connection.execute(text(query))}
        finally:
            await engine.dispose()

    return asyncio.run(run())


def recreate_database() -> None:
    async def run() -> None:
        engine = create_async_engine(
            url_for("postgres"), isolation_level="AUTOCOMMIT", poolclass=NullPool
        )
        try:
            async with engine.connect() as connection:
                await connection.execute(text(f'drop database if exists "{DATABASE}"'))
                await connection.execute(text(f'create database "{DATABASE}"'))
        finally:
            await engine.dispose()

    asyncio.run(run())


@pytest.fixture
def scratch() -> str:
    recreate_database()
    return url_for(DATABASE)


@pytest.fixture
def config(scratch):
    return alembic_config(scratch)


def test_upgrade_builds_the_whole_schema_from_empty(config, scratch):
    command.upgrade(config, "head")

    assert names(scratch, TABLES) == {
        "alembic_version",
        "submissions",
        "extractions",
        "enrichments",
        "ratings",
        "quotes",
        "audit_events",
    }
    assert len(names(scratch, ENUM_TYPES)) == 10


def test_downgrade_leaves_no_tables_and_no_enum_types(config, scratch):
    command.upgrade(config, "head")
    command.downgrade(config, "base")

    # DROP TABLE leaves enum types behind, so this is the assertion that matters.
    assert names(scratch, TABLES) == {"alembic_version"}
    assert names(scratch, ENUM_TYPES) == set()


def test_upgrade_downgrade_upgrade_round_trips(config, scratch):
    command.upgrade(config, "head")
    command.downgrade(config, "base")
    command.upgrade(config, "head")

    assert "submissions" in names(scratch, TABLES)
    assert names(scratch, "select version_num from alembic_version") == {"0001"}


def test_migrations_match_the_models(config):
    command.upgrade(config, "head")

    # Adding a column without a migration fails here rather than in production.
    try:
        command.check(config)
    except AutogenerateDiffsDetected as drift:
        pytest.fail(f"models and migrations disagree: {drift}")
