"""Synchronous by design: env.py calls asyncio.run, which raises inside a running loop."""

import asyncio

import pytest
from alembic import command
from sqlalchemy import text
from sqlalchemy.engine import make_url
from sqlalchemy.ext.asyncio import create_async_engine
from sqlalchemy.pool import NullPool

from tests.conftest import alembic_config, derive_test_database_url

DATABASE = "underwrite_migrations_test"

TABLES = "select table_name from information_schema.tables where table_schema = 'public'"
TRIGGERS = """
select t.tgname from pg_trigger t
join pg_class c on c.oid = t.tgrelid
join pg_namespace n on n.oid = c.relnamespace
where n.nspname = 'public' and not t.tgisinternal
"""
FUNCTIONS = "select proname from pg_proc where proname = 'refuse_audit_mutation'"
ENUM_TYPES = """
select t.typname from pg_type t
join pg_namespace n on n.oid = t.typnamespace
where n.nspname = 'public' and t.typtype = 'e'
"""


def url_for(database: str) -> str:
    return (
        make_url(derive_test_database_url())
        .set(database=database)
        .render_as_string(hide_password=False)
    )


def names(url: str, query: str) -> set[str]:
    async def run() -> set[str]:
        engine = create_async_engine(url, poolclass=NullPool)
        try:
            async with engine.connect() as connection:
                return {row[0] for row in await connection.execute(text(query))}
        finally:
            await engine.dispose()

    return asyncio.run(run())


def recreate_database() -> None:
    async def run() -> None:
        engine = create_async_engine(
            url_for("postgres"), isolation_level="AUTOCOMMIT", poolclass=NullPool
        )
        try:
            async with engine.connect() as connection:
                await connection.execute(text(f'drop database if exists "{DATABASE}"'))
                await connection.execute(text(f'create database "{DATABASE}"'))
        finally:
            await engine.dispose()

    asyncio.run(run())


@pytest.fixture(scope="module")
def scratch() -> str:
    recreate_database()
    return url_for(DATABASE)


@pytest.fixture
def config(scratch):
    config = alembic_config(scratch)
    yield config
    # Rewound rather than recreated: create database copies template1 and is slow.
    command.downgrade(config, "base")


def test_upgrade_builds_the_whole_schema_from_empty(config, scratch):
    command.upgrade(config, "head")

    assert names(scratch, TABLES) == {
        "alembic_version",
        "submissions",
        "extractions",
        "enrichments",
        "ratings",
        "quotes",
        "audit_events",
    }
    assert names(scratch, TRIGGERS) == {"audit_events_append_only", "audit_events_no_truncate"}
    assert names(scratch, FUNCTIONS) == {"refuse_audit_mutation"}
    assert names(scratch, ENUM_TYPES) == {
        "audit_actor",
        "audit_event_type",
        "company_status",
        "data_volume",
        "decision",
        "input_mode",
        "quote_status",
        "requested_limit",
        "sector",
        "submission_status",
    }


def test_downgrade_leaves_no_tables_and_no_enum_types(config, scratch):
    command.upgrade(config, "head")
    command.downgrade(config, "base")

    # DROP TABLE leaves enum types behind, so this is the assertion that matters.
    assert names(scratch, TABLES) == {"alembic_version"}
    assert names(scratch, ENUM_TYPES) == set()
    # The function is schema-level and outlives its table, so it needs its own DROP.
    assert names(scratch, FUNCTIONS) == set()
    assert names(scratch, TRIGGERS) == set()


def test_upgrade_downgrade_upgrade_round_trips(config, scratch):
    command.upgrade(config, "head")
    command.downgrade(config, "base")
    command.upgrade(config, "head")

    assert "submissions" in names(scratch, TABLES)
    assert names(scratch, "select version_num from alembic_version") == {"0002"}


def test_migrations_match_the_models(config):
    command.upgrade(config, "head")

    # Raises AutogenerateDiffsDetected naming the column if a model changed without one.
    command.check(config)
