/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Submissions */
        get: operations["list_submissions_api_submissions_get"];
        put?: never;
        /** Create Submission */
        post: operations["create_submission_api_submissions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submissions/{submission_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Submission */
        get: operations["get_submission_api_submissions__submission_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_api_documents__key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AuditActor
         * @enum {string}
         */
        AuditActor: "system" | "ops" | "applicant";
        /** AuditEventRead */
        AuditEventRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            event_type: components["schemas"]["AuditEventType"];
            actor: components["schemas"]["AuditActor"];
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
        };
        /**
         * AuditEventType
         * @enum {string}
         */
        AuditEventType: "submission_received" | "extraction_completed" | "extraction_failed" | "enrichment_completed" | "enrichment_failed" | "rating_completed" | "rating_failed" | "submission_approved" | "submission_declined" | "quote_generated" | "quote_render_failed" | "quote_expired" | "bordereau_exported";
        /**
         * CompanyStatus
         * @enum {string}
         */
        CompanyStatus: "active" | "dissolved" | "liquidation" | "receivership" | "administration" | "voluntary-arrangement" | "converted-closed" | "insolvency-proceedings" | "registered" | "removed" | "closed" | "open";
        /**
         * DataVolume
         * @enum {string}
         */
        DataVolume: "under_10k" | "10k_100k" | "100k_1m" | "over_1m";
        /**
         * Decision
         * @enum {integer}
         */
        Decision: 0 | 1 | 2;
        /** EnrichmentRead */
        EnrichmentRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Ch Found */
            ch_found: boolean;
            /** Ch Company Number */
            ch_company_number: string | null;
            /** Ch Company Name */
            ch_company_name: string | null;
            ch_company_status: components["schemas"]["CompanyStatus"] | null;
            /** Ch Company Status Detail */
            ch_company_status_detail: string | null;
            /** Ch Date Of Creation */
            ch_date_of_creation: string | null;
            /** Ch Name Match Score */
            ch_name_match_score: number | null;
            /** Sic Codes */
            sic_codes: string[];
            /** Discrepancies */
            discrepancies: string[];
            /** Rate Limited */
            rate_limited: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ExtractedApplication
         * @description The `messages.parse()` output format — broker units, not storage units.
         */
        ExtractedApplication: {
            /** Company Name */
            company_name?: string | null;
            /** Company Number */
            company_number?: string | null;
            sector?: components["schemas"]["Sector"] | null;
            /** Annual Revenue Gbp */
            annual_revenue_gbp?: number | null;
            /** Years Trading */
            years_trading?: number | null;
            /** Prior Claims Count */
            prior_claims_count?: number | null;
            data_records_held?: components["schemas"]["DataVolume"] | null;
            requested_limit_gbp?: components["schemas"]["RequestedLimit"] | null;
            /** Extraction Confidence */
            extraction_confidence: number;
            /** Missing Fields */
            missing_fields?: string[];
        };
        /** ExtractionRead */
        ExtractionRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Company Name */
            company_name: string | null;
            /** Company Number */
            company_number: string | null;
            sector: components["schemas"]["Sector"] | null;
            /** Annual Revenue Pence */
            annual_revenue_pence: number | null;
            /** Months Trading */
            months_trading: number | null;
            /** Prior Claims Count */
            prior_claims_count: number | null;
            data_records_held: components["schemas"]["DataVolume"] | null;
            requested_limit: components["schemas"]["RequestedLimit"] | null;
            /** Extraction Confidence */
            extraction_confidence: number;
            /** Missing Fields */
            missing_fields: string[];
            /** Model */
            model: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** FactorRead */
        FactorRead: {
            /** Code */
            code: string;
            /** Band Label */
            band_label: string;
            /** Multiplier */
            multiplier: string;
            /** Reason */
            reason: string;
            /** Premium Before Pence */
            premium_before_pence: string;
            /** Premium After Pence */
            premium_after_pence: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InputMode
         * @enum {string}
         */
        InputMode: "form" | "paste" | "pdf_upload";
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** QuoteRead */
        QuoteRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Quote Ref */
            quote_ref: string;
            status: components["schemas"]["QuoteStatus"];
            /** Limit Pence */
            limit_pence: number;
            /** Excess Pence */
            excess_pence: number;
            /** Gross Premium Pence */
            gross_premium_pence: number;
            /**
             * Inception Date
             * Format: date
             */
            inception_date: string;
            /**
             * Valid Until
             * Format: date
             */
            valid_until: string;
            /** Pdf S3 Key */
            pdf_s3_key: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * QuoteStatus
         * @enum {string}
         */
        QuoteStatus: "issued" | "expired";
        /** RatingRead */
        RatingRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Rating Version */
            rating_version: string;
            decision: string;
            /** Base Premium Pence */
            base_premium_pence: number;
            /** Indicative Premium Pence */
            indicative_premium_pence: number;
            /** Annual Premium Pence */
            annual_premium_pence: number | null;
            /** Factors */
            factors: components["schemas"]["FactorRead"][];
            /** Refer Reasons */
            refer_reasons: components["schemas"]["ReasonRead"][];
            /** Decline Reasons */
            decline_reasons: components["schemas"]["ReasonRead"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ReasonCode
         * @enum {string}
         */
        ReasonCode: "LOW_EXTRACTION_CONFIDENCE" | "MISSING_FIELDS" | "CH_NOT_FOUND" | "CH_NAME_MISMATCH" | "CH_STATUS_NOT_ACTIVE" | "CH_DISCREPANCY" | "REVENUE_ABOVE_AUTHORITY" | "SECTOR_UNCLASSIFIED" | "PRIOR_CLAIM" | "SECTOR_OUT_OF_APPETITE" | "CLAIMS_HISTORY" | "TOO_NEW" | "CH_STATUS_TERMINAL";
        /** ReasonRead */
        ReasonRead: {
            code: components["schemas"]["ReasonCode"];
            /** Message */
            message: string;
        };
        /**
         * RequestedLimit
         * @enum {integer}
         */
        RequestedLimit: 250000 | 500000 | 1000000 | 2000000;
        /**
         * Sector
         * @enum {string}
         */
        Sector: "saas" | "fintech" | "healthtech" | "ecommerce" | "ai_ml" | "marketplace" | "crypto" | "other";
        /** SubmissionCreate */
        SubmissionCreate: {
            input_mode: components["schemas"]["InputMode"];
            /** Raw Input */
            raw_input?: string | null;
            application?: components["schemas"]["ExtractedApplication"] | null;
        };
        /** SubmissionDetail */
        SubmissionDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            status: components["schemas"]["SubmissionStatus"];
            input_mode: components["schemas"]["InputMode"];
            /** Raw Input */
            raw_input: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            extraction?: components["schemas"]["ExtractionRead"] | null;
            enrichment?: components["schemas"]["EnrichmentRead"] | null;
            rating?: components["schemas"]["RatingRead"] | null;
            quote?: components["schemas"]["QuoteRead"] | null;
            /** Audit Events */
            audit_events?: components["schemas"]["AuditEventRead"][];
        };
        /** SubmissionListItem */
        SubmissionListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            status: components["schemas"]["SubmissionStatus"];
            input_mode: components["schemas"]["InputMode"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Company Name */
            company_name: string | null;
            /** Company Number */
            company_number: string | null;
            sector: components["schemas"]["Sector"] | null;
            /** Annual Revenue Pence */
            annual_revenue_pence: number | null;
            requested_limit: components["schemas"]["RequestedLimit"] | null;
            /** Premium Pence */
            premium_pence: number | null;
            decision: string | null;
            /** Headline */
            headline: string | null;
        };
        /**
         * SubmissionStatus
         * @enum {string}
         */
        SubmissionStatus: "received" | "failed" | "auto_approved" | "referred" | "declined" | "quoted";
        /** UserRead */
        UserRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Username */
            username: string;
            /** Display Name */
            display_name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    list_submissions_api_submissions_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["SubmissionStatus"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_submission_api_submissions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmissionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_submission_api_submissions__submission_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_api_documents__key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
